### ISSUE TITLE
Uncaught TypeError: Cannot read property 'ready' of undefined

### ISSUE THREAD

**Issue by jamilce** [rogeriotaques/mytour#1]
I am getting error in chrome console. Kindly resolve it.

jquery.1.7.1.js: 2 Uncaught TypeError: Cannot read property 'ready' of undefined
    at HTMLDocument.init (jquery.1.7.1.js:2)
    at n (jquery.1.7.1.js:2)
    at Object.add (jquery.1.7.1.js:2)
    at init.ready (jquery.1.7.1.js:2)

**Comment by rogeriotaques** [comment]
Hi, @jamilce! I'm really sorry about that. Unfortunately, this plugin was discontinued about 2 years ago and I'm just keeping its code online for reference. Anyway, I'd be very glad on help you fixing that bug, but I'm a little bit overloaded on these days, so, if you're not in a hurry I may look into that when I have a spare time. If it's urgent for you, I'd suggest you have a look on this other plugin: https://github.com/rogeriotaques/hopscotch.

**Comment by jamilce** [comment]
Thanks for getting back to me.
No worries , will follow other plugins.
